### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by pioto1225** [robjinman/gemsnrocks_asm#1]
Hi Rob,

Your post on LinkedIn made me interested and I gave it a go. I tried it on the host and it did not run, hitting segmentation fault in main.asm:857. Maybe it has to do with the screen resolution which is 4k and I did not know how to reduce it for TTY. 
It runs fine in a VM with smaller screen. No need to fix anything, I am not gonna play the game. But the idea and the result is nice!

cheers,
Piotr

**Comment by robjinman** [comment]
Hi Piotr, thanks, I'll look into it when I get a chance.

**Comment by robjinman** [comment]
Should be fixed now. The problem was that I hadn't considered the possibility that the screen size could be larger than the game map.

**Comment by pioto1225** [comment]
yes, it works, thanks!
